### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by staminna** [gordalina/faced#12]
After updating and running homebrew, everything works as expected until npm
`$ npm install -g faced

> opencv@6.0.0 install /Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-opencv.s3.amazonaws.com/opencv/v6.0.0/Release/node-v46-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for opencv@6.0.0 and node@4.8.0 (node-v46 ABI, unknown) (falling back to source compile with node-gyp) 
/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/utils/find-opencv.js:21
                throw new Error("ERROR: failed to run: pkg-config", opencv, flag);
                ^

Error: ERROR: failed to run: pkg-config
    at /Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/utils/find-opencv.js:21:23
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Socket.<anonymous> (internal/child_process.js:330:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:487:12)
gyp: Call to 'node utils/find-opencv.js --cflags' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/jorge/.nvm/versions/node/v4.8.0/bin/node" "/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/build/opencv/v6.0.0/Release/node-v46-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/build/opencv/v6.0.0/Release/node-v46-darwin-x64"
gyp ERR! cwd /Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv
gyp ERR! node -v v4.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jorge/.nvm/versions/node/v4.8.0/bin/node /Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/build/opencv/v6.0.0/Release/node-v46-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/build/opencv/v6.0.0/Release/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:854:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/Users/jorge/.nvm/versions/node/v4.8.0/bin/node" "/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv
node-pre-gyp ERR! node -v v4.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/jorge/.nvm/versions/node/v4.8.0/bin/node /Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/build/opencv/v6.0.0/Release/node-v46-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/jorge/.nvm/versions/node/v4.8.0/lib/node_modules/faced/node_modules/opencv/build/opencv/v6.0.0/Release/node-v46-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above`

**Comment by kentos** [comment]
Same here :'(

**Comment by Robula** [comment]
Related:
https://github.com/peterbraden/node-opencv/issues/482
https://github.com/peterbraden/node-opencv/issues/562
https://github.com/peterbraden/node-opencv/issues/538
https://github.com/peterbraden/node-opencv/issues/478
https://github.com/peterbraden/node-opencv/issues/472
https://github.com/peterbraden/node-opencv/issues/463

**Comment by Robula** [comment]
I got my environment working, here are the steps:
1. Install `pkg-config` and `opencv@2`: `brew install pkg-config opencv@2`.
2. Remove node_modules and any lock files: `rm -rf node_modules`.
3. Run npm/yarn install: `yarn`.

**Comment by lixin2628** [comment]
Same here :'(

**Comment by harryyuanfeng** [comment]
@Robula I have tried your steps and still getting error. 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/build/opencv/v6.0.0/Release/node-v59-darwin-x64/opencv.node" "--module_name=opencv" "--module_path=/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/build/opencv/v6.0.0/Release/node-v59-darwin-x64"
gyp ERR! cwd /Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv
gyp ERR! node -v v9.6.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/build/opencv/v6.0.0/Release/node-v59-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/build/opencv/v6.0.0/Release/node-v59-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:933:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv
node-pre-gyp ERR! node -v v9.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/build/opencv/v6.0.0/Release/node-v59-darwin-x64/opencv.node --module_name=opencv --module_path=/Users/harryfeng/Downloads/old/angelaBaby/node_modules/opencv/build/opencv/v6.0.0/Release/node-v59-darwin-x64' (1)
npm WARN angelababy@1.0.0 No description
npm WARN angelababy@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@6.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/harryfeng/.npm/_logs/2018-03-07T15_31_25_085Z-debug.log
```

**Comment by harryyuanfeng** [comment]
problem is form opencv. We need to wait opencv to update. Temp solution I found:

1. git clone https://github.com/gordalina/faced.git
2. cd faced
3. update package.json, "opencv": "^5.0.0",
4. cd ..
5. npm install faced/

**Comment by gordalina** [comment]
Fixed the installation steps. 
- Make sure `package.json` has `opencv ^5` as @harryyuanfeng suggested
- Makre sure brew installs `pkg-config` and `opencv@2` and its linked as @Robula suggested

Released `1.2.2`
