### ISSUE TITLE
Error trying to run the example

### ISSUE THREAD

**Issue by thalesfsp** [gordalina/faced#4]
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2cv17CascadeClassifier4loadERKSs
  Referenced from: /Users/XXX/Dev/opencv/node_modules/faced/node_modules/opencv/build/Release/opencv.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2cv17CascadeClassifier4loadERKSs
  Referenced from: /Users/XXX/Dev/opencv/node_modules/faced/node_modules/opencv/build/Release/opencv.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

**Comment by dchacke** [comment]
I'm getting the same issue:

```shell
dyld: lazy symbol binding failed: Symbol not found: __ZN2cv17CascadeClassifier4loadERKSs
  Referenced from: /Developer/JavaScript/babel/node_modules/faced/node_modules/opencv/build/Release/opencv.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2cv17CascadeClassifier4loadERKSs
  Referenced from: /Developer/JavaScript/babel/node_modules/faced/node_modules/opencv/build/Release/opencv.node
  Expected in: dynamic lookup

[1]    25936 trace trap  node index.js
```

**Comment by MalvinMiao** [comment]
I get the similar issue here, when I try to run the "identify.js" example, I get the error below:
module.js:327
    throw err;
    ^

Error: Cannot find module '../build/Release/opencv.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/faced/node_modules/opencv/lib/bindings.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

I installed opencv 3.0.0 and it wokrs well, any idea for this? Thank you in advance
